### ISSUE TITLE
As a user, I want to see my name while playing the game

### ISSUE THREAD

**Issue by atees4836** [atees4836/3760Project#26]

**Comment by cbrenn05** [comment]
@atees4836 @AlexChin0 @JJgotBored The names work now, here's some screenshots showing how they work.
![names.PNG](https://zube.io/files/atees4836/3d3a7fb4459c3e6dde24a52dcdbdc1ee-names.png)![names-filled-in.PNG](https://zube.io/files/atees4836/cb9d8753de6c79b4a5e81de8c0dc2ca4-names-filled-in.png)![names-board.PNG](https://zube.io/files/atees4836/530c20e4c426edf3e44ba2562ff8c59f-names-board.png)
