### ISSUE TITLE
Test Case 1: Game Build (Retest)

### ISSUE THREAD

**Issue by cbrenn05** [atees4836/3760Project#28]
As a user I want to be able to open the game.

**_When _**a desktop build is run, 
**_then_** the game loads and the main menu screen displays.

Please capture screenshots of successful test case, or provide comments on unsuccessful test cases and move to  'In Review'.

**Comment by atees4836** [comment]
Build and run selected from menu:
![Screen Shot 2021-11-05 at 12.47.14 PM.png](https://zube.io/files/atees4836/97f694c66314af4351343d5c5142daf7-screen-shot-2021-11-05-at-12-47-14-pm.png)
Game build:
![Screen Shot 2021-11-05 at 12.45.34 PM.png](https://zube.io/files/atees4836/8f674a606ec1187558001646ff1dc267-screen-shot-2021-11-05-at-12-45-34-pm.png)
