### ISSUE TITLE
Test Case 2: Names Scene

### ISSUE THREAD

**Issue by cbrenn05** [atees4836/3760Project#29]
As a user I want to view a player name input screen.

**_When _** the game is run and the 'New Game' button is clicked,
**_then_** the 'Names' scene displays, 
**_and_** two name input fields show, as well as a submit button.

Please capture screenshots of successful test case, or provide comments on unsuccessful test cases and move to  'In Review'.

**Comment by AlexChin0** [comment]
Game menu before test case:
![test1beeefore.PNG](https://zube.io/files/atees4836/4a3bfcce0f6382945fba210bb7cb57ec-test1beeefore.png)

Names scene display after test case (successful): 
![tteest1after.PNG](https://zube.io/files/atees4836/5106de127d20f525d7e54d663fbe366a-tteest1after.png)

The button worked and both name fields are displayed.
