### ISSUE TITLE
Test Case 3: Name Input

### ISSUE THREAD

**Issue by cbrenn05** [atees4836/3760Project#30]
As a user, I want to be able to enter my player's name.

**_Given _** the game is run and the user navigates to the Names scene, 
**_when_** the user clicks on a name input field,
**_then_** the user is able to enter a name on their keyboard
**_and_** it will show up as text in the input field.

Please capture screenshots of successful test case, or provide comments on unsuccessful test cases and move to  'In Review'.

**Comment by AlexChin0** [comment]
Game board with player names displaying properly:
![image.png](https://zube.io/files/atees4836/c2a6d1a9b9598889c7706d2cc6691444-image.png)
