### ISSUE TITLE
Test Case 4: Name Propagation (4 subtests)

### ISSUE THREAD

**Issue by cbrenn05** [atees4836/3760Project#31]
As a user I want to see the player name's I have inputted on the board.

**_Given _** the game is run and the user has inputted a name in the 'Player 1 Name' field and leaves the  'Player 2 name' field blank,
**_when_** the user clicks the 'submit' button on the 'Names' scene, 
**_then_** the inputted name displays next to the 'Player 1: ' text in the 'board' scene,
**_and_** the 'Player 2: ' text displays with no extra text beside it.

**_Given _** the game is run and the user has inputted a name in the 'Player 2 Name' field and leaves the  'Player 1 name' field blank,
**_when_** the user clicks the 'submit' button on the 'Names' scene, 
**_then_** the inputted name displays next to the 'Player 2: ' text in the 'board' scene,
**_and_** the 'Player 1: ' text displays with no extra text beside it.

**_Given _** the game is run and the user has inputted a name in both the 'Player 1 Name' field and the 'Player 2 Name' field,
**_when_** the user clicks the 'submit' button on the 'Names' scene, 
**_then_** the inputted names display next to the 'Player 1: ' and 'Player 2' texts in the 'board' scene.

**_Given _** the game is run and the user has not inputted any names,
**_when_** the user clicks the 'submit' button on the 'Names' scene, 
**_then_** the 'Player 1: ' and the 'Player 2' texts display with no extra text beside them.

Please capture screenshots of successful test case, or provide comments on unsuccessful test cases and move to  'In Review'.

**Comment by JJgotBored** [comment]
Subtest 1: the game is run and the user has inputted a name in the 'Player 1 Name' field and leaves the 'Player 2 name' field blank
![image.png](https://zube.io/files/atees4836/57f8a897e06f0840c7610ec2dd422fa7-image.png)
![image.png](https://zube.io/files/atees4836/921f846e021666d25f4de8d66a4f87a9-image.png)
![image.png](https://zube.io/files/atees4836/e8447666e3fa1d24605a3f7768fc3550-image.png)

Subtest 2: the game is run and the user has inputted a name in the 'Player 2 Name' field and leaves the 'Player 1 name' field blank
![image.png](https://zube.io/files/atees4836/f25bd0d38a343a934076e78ab1b24971-image.png)
![image.png](https://zube.io/files/atees4836/e887ea9334d87af2b8751b5eae174d63-image.png)

Subtest 3: the game is run and the user has inputted a name in both the 'Player 1 Name' field and the 'Player 2 Name' field
![image.png](https://zube.io/files/atees4836/a476dc1ff7bd1918a489ffc5b58a8e4e-image.png)
![image.png](https://zube.io/files/atees4836/8063341603c716942ce108d9c683615f-image.png)

Subtest 4: the game is run and the user has not inputted any names
![image.png](https://zube.io/files/atees4836/e336f350b2602082c2b23b7daa6a4a5d-image.png)
![image.png](https://zube.io/files/atees4836/00924c95e1bd1c0b8ab9fdd56c6cd095-image.png)
