### ISSUE TITLE
Test Case 5: Instructions Scene (2 subtests)

### ISSUE THREAD

**Issue by cbrenn05** [atees4836/3760Project#32]
As a user, I want to be able to learn the rules of the game

**_Given _** the game is run,
**_when_** the user clicks on the 'How To Play' button,
**_then_** the 'Instructions' scene displays with the text instructions of the game. 

**_Given _** the game is run and the user has navigated to the 'How To Play' scene,
**_when_** the user clicks on the 'back' button,
**_then_** the user is returned to the 'main menu' scene.

Please capture screenshots of successful test case, or provide comments on unsuccessful test cases and move to  'In Review'.

**Comment by JJgotBored** [comment]
Subtest 1: the user clicks on the 'How To Play' button
![image.png](https://zube.io/files/atees4836/ec4a4f423b477c66d1b9c7006276f6a6-image.png)
![image.png](https://zube.io/files/atees4836/6f2b72614803c60c600bce9143519942-image.png)

Subtest 2: return to main menu
![image.png](https://zube.io/files/atees4836/6f2b72614803c60c600bce9143519942-image.png)
![image.png](https://zube.io/files/atees4836/7283ee23bb0aa38145e4d2686836d5f4-image.png)
