### ISSUE TITLE
Test Case 8: One Piece per Square (4 subtests)

### ISSUE THREAD

**Issue by cbrenn05** [atees4836/3760Project#35]
As a user, I would like to be able have a square only occupy one square at a time.

**_Given _** the game is run and the game is started (user is at 'board' scene),
**_and_** it is the Player 1's turn, the user selects a piece,
**_when_** the user clicks on a location on the left diagonal that is occupied,
**_then_** the selected piece does not move to that location. 

**_Given _** the game is run and the game is started (user is at 'board' scene),
**_and_** it is the Player 1's turn, the user selects a piece,
**_when_** the user clicks on a location on the right diagonal that is occupied,
**_then_** the selected piece does not move to that location. 

**_Given _** the game is run and the game is started (user is at 'board' scene),
**_and_** it is the Player 2's turn, the user selects a piece,
**_when_** the user clicks on a location on the left diagonal that is occupied,
**_then_** the selected piece does not move to that location. 

**_Given _** the game is run and the game is started (user is at 'board' scene),
**_and_** it is the Player 2's turn, the user selects a piece,
**_when_** the user clicks on a location on the right diagonal that is occupied,
**_then_** the selected piece does not move to that location. 

Please capture screenshots of successful test case, or provide comments on unsuccessful test cases and move to  'In Review'.

**Comment by atees4836** [comment]
Subtest 1: 
Piece selected: 
![Screen Shot 2021-11-05 at 12.41.05 PM.png](https://zube.io/files/atees4836/4865db927fdc37248bce987f5f30e676-screen-shot-2021-11-05-at-12-41-05-pm.png)
Occupied square clicked:
![Screen Shot 2021-11-05 at 12.41.20 PM.png](https://zube.io/files/atees4836/43ec13f9009d850dd23c63f5e7600fcc-screen-shot-2021-11-05-at-12-41-20-pm.png)

**Comment by atees4836** [comment]
Subtest 2:
Piece selected:
![Screen Shot 2021-11-05 at 12.49.17 PM.png](https://zube.io/files/atees4836/4259511c946a2b69c804747da15f855c-screen-shot-2021-11-05-at-12-49-17-pm.png)
Occupied square selected:
![Screen Shot 2021-11-05 at 12.49.28 PM.png](https://zube.io/files/atees4836/82596023aa6f968fb1057ad3b782d046-screen-shot-2021-11-05-at-12-49-28-pm.png)

**Comment by atees4836** [comment]
Subtest 3:
Piece selected:
![Screen Shot 2021-11-05 at 12.51.00 PM.png](https://zube.io/files/atees4836/638a571b703f18ec6f1216c9cedfca4c-screen-shot-2021-11-05-at-12-51-00-pm.png)
Occupied square chosen: 
![Screen Shot 2021-11-05 at 12.51.08 PM.png](https://zube.io/files/atees4836/b66b2ffd5af8e43683e8b63a4d169927-screen-shot-2021-11-05-at-12-51-08-pm.png)

**Comment by atees4836** [comment]
Subtest 4:
Piece selected:
![Screen Shot 2021-11-05 at 12.51.00 PM.png](https://zube.io/files/atees4836/638a571b703f18ec6f1216c9cedfca4c-screen-shot-2021-11-05-at-12-51-00-pm.png)
Occupied square chosen: 
![Screen Shot 2021-11-05 at 12.53.47 PM.png](https://zube.io/files/atees4836/a4ec183bde3dc3ec24117099cddceee8-screen-shot-2021-11-05-at-12-53-47-pm.png)
