### ISSUE TITLE
Test Case 9: Basic Piece Capture (no king pieces, no multi-capture) (4 subtests)

### ISSUE THREAD

**Issue by cbrenn05** [atees4836/3760Project#36]
As a user, I would like to be able to capture my opponent's pieces.

**_Given _** the game is run and the game is started (user is at 'board' scene),
**_and_** it is the Player 1's turn, the user selects a piece, and there is a legal capture move to the left diagonal,
**_when_** the user clicks on the capture location on the left diagonal,
**_then_** the selected piece moves to that location and the opponent piece disappears.

**_Given _** the game is run and the game is started (user is at 'board' scene),
**_and_** it is the Player 1's turn, the user selects a piece, and there is a legal capture move to the right diagonal,
**_when_** the user clicks on the capture location on the right diagonal,
**_then_** the selected piece moves to that location and the opponent piece disappears.

**_Given _** the game is run and the game is started (user is at 'board' scene),
**_and_** it is the Player 2's turn, the user selects a piece, and there is a legal capture move to the left diagonal,
**_when_** the user clicks on the capture location on the left diagonal,
**_then_** the selected piece moves to that location and the opponent piece disappears.

**_Given _** the game is run and the game is started (user is at 'board' scene),
**_and_** it is the Player 2's turn, the user selects a piece, and there is a legal capture move to the right diagonal,
**_when_** the user clicks on the capture location on the right diagonal,
**_then_** the selected piece moves to that location and the opponent piece disappears.

Please capture screenshots of successful test case, or provide comments on unsuccessful test cases and move to  'In Review'.

**Comment by atees4836** [comment]
Subtest 1:
Before capture:
![Screen Shot 2021-11-05 at 12.57.07 PM.png](https://zube.io/files/atees4836/82bfbc4a2b4ca6ef687821955349bf2f-screen-shot-2021-11-05-at-12-57-07-pm.png)
After capture:
![Screen Shot 2021-11-05 at 12.57.17 PM.png](https://zube.io/files/atees4836/945689445f9ce52428b47a393661cb12-screen-shot-2021-11-05-at-12-57-17-pm.png)

**Comment by atees4836** [comment]
Subtest 2:
Before capture:
![Screen Shot 2021-11-05 at 12.59.21 PM.png](https://zube.io/files/atees4836/c9664c13d6e9944d74f510d03938821a-screen-shot-2021-11-05-at-12-59-21-pm.png)
After capture:
![Screen Shot 2021-11-05 at 12.59.35 PM.png](https://zube.io/files/atees4836/f55481c14e08e1d0c9bb307411a71e1a-screen-shot-2021-11-05-at-12-59-35-pm.png)

**Comment by atees4836** [comment]
Subtest 3:
Before capture:
![Screen Shot 2021-11-05 at 1.00.48 PM.png](https://zube.io/files/atees4836/8212d55435ad19a0bf3a3f02ee99ee05-screen-shot-2021-11-05-at-1-00-48-pm.png)
After capture:
![Screen Shot 2021-11-05 at 1.00.52 PM.png](https://zube.io/files/atees4836/cd793863dbe3f56a64af378f6e413f2d-screen-shot-2021-11-05-at-1-00-52-pm.png)

**Comment by atees4836** [comment]
Subtest 4:
Before capture:
![Screen Shot 2021-11-05 at 2.12.03 PM.png](https://zube.io/files/atees4836/53ae8b9244f36131686f85274a6b5f68-screen-shot-2021-11-05-at-2-12-03-pm.png)
After capture:
![Screen Shot 2021-11-05 at 2.12.12 PM.png](https://zube.io/files/atees4836/156e6aa5a2c53c451c3cafb6a5aed93e-screen-shot-2021-11-05-at-2-12-12-pm.png)
