### ISSUE TITLE
As a user, I want to view the game board

### ISSUE THREAD

**Issue by atees4836** [atees4836/3760Project#4]
- [ ] Draw game board
- [ ]  atees4836/3760Project#12

**Comment by cbrenn05** [comment]
Very basic code is done for this. I've made a game board out of 2D square sprites, and both sets of gamepieces, plus put a background.  Pieces are labelled alphanumerically in the gameobject panel, starting with A1 on the top left corner (letters go vertically, numbers horizontally). Game pieces are labelled R1 - R12 and B1 - B12 based on colour.

**Comment by AlexChin0** [comment]
We should probably refactor the board at some board as a simple sprite, something like this.![checkas.png](https://zube.io/files/atees4836/8e1d177a665c968fa61798bbc2811b83-checkas.png)
