### ISSUE TITLE
Test Case 4: Game Over

### ISSUE THREAD

**Issue by cbrenn05** [atees4836/3760Project#42]
As a user, I want to be notified when the game has ended.

**_Given _** the game has ended (no legal moves left),
**_then_** a 'game over' window appears.

Please capture screenshots of successful test case, or provide comments on unsuccessful test cases and move to  'In Review'.

**Comment by atees4836** [comment]
Before last capture:
![Screen Shot 2021-11-27 at 3.19.49 PM.png](https://zube.io/files/atees4836/c189f47106b8fbbc744eec8af886b001-screen-shot-2021-11-27-at-3-19-49-pm.png)
After last capture: 
![Screen Shot 2021-11-27 at 3.20.07 PM.png](https://zube.io/files/atees4836/e0213c62b78c9d3b6c9a77308403e043-screen-shot-2021-11-27-at-3-20-07-pm.png)
